// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvgPabc2TeTBXM5kjmcs9LysVogkGa3SM',
    appId: '1:527057731588:web:3e5032a9615e8a9fbc3551',
    messagingSenderId: '527057731588',
    projectId: 'live-5e192',
    authDomain: 'live-5e192.firebaseapp.com',
    storageBucket: 'live-5e192.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgyyau0nJROLlxYIzXcgAn162TLyfxP5I',
    appId: '1:527057731588:android:d766eb522a22675abc3551',
    messagingSenderId: '527057731588',
    projectId: 'live-5e192',
    storageBucket: 'live-5e192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wqF0GPyF1kdtQZdrMWxEvVJqe5UifEw',
    appId: '1:527057731588:ios:2ffef101356b9386bc3551',
    messagingSenderId: '527057731588',
    projectId: 'live-5e192',
    storageBucket: 'live-5e192.firebasestorage.app',
    iosBundleId: 'com.incodes.shortie.live',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wqF0GPyF1kdtQZdrMWxEvVJqe5UifEw',
    appId: '1:527057731588:ios:f0a993c0885f5fb7bc3551',
    messagingSenderId: '527057731588',
    projectId: 'live-5e192',
    storageBucket: 'live-5e192.firebasestorage.app',
    iosBundleId: 'com.incodes.shortie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvgPabc2TeTBXM5kjmcs9LysVogkGa3SM',
    appId: '1:527057731588:web:5b6f81b9ba7f948abc3551',
    messagingSenderId: '527057731588',
    projectId: 'live-5e192',
    authDomain: 'live-5e192.firebaseapp.com',
    storageBucket: 'live-5e192.firebasestorage.app',
  );
}
